# MSDS 432, Assignment 9 - Dynamic Programming

#### Author: Brandon Moretz

In [11]:
%matplotlib inline

In [108]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from time import time
import matplotlib.style as style

In [109]:
np.random.seed(323) # static seed so results are reproducible

In [110]:
style.use('seaborn-poster') # sets the size of the charts
style.use('ggplot') # set the theme for matplotlib

In [111]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

<IPython.core.display.Javascript object>

## Algorithm

In [131]:
def diceThrow(n, faces, total):
    dp = np.zeros(( n + 1, total + 1))
    
    dp[0, 0] = 1
    
    for i in range(1, n + 1):
        for j in range(1, total + 1):
            if j < i:
                dp[i, j] = 0
            elif j > ( faces * i ):
                dp[i, j] = 0
            else:
                k = 1
                while k <= faces and j >= k:
                    dp[i, j] += dp[i-1, j-k]
                    k += 1
                    
    return( dp[n][total], dp )

## Setup

In [134]:
die = 6
faces = 3
total = 8

## Results

In [135]:
ans = diceThrow(die, faces, total)

In [136]:
# Resulting Matrix
print(ans[1])

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  2.  3.  2.  1.  0.  0.]
 [ 0.  0.  0.  1.  3.  6.  7.  6.  3.]
 [ 0.  0.  0.  0.  1.  4. 10. 16. 19.]
 [ 0.  0.  0.  0.  0.  1.  5. 15. 30.]
 [ 0.  0.  0.  0.  0.  0.  1.  6. 21.]]


In [137]:
print('Number of ways {0} die can be thrown to sum {1} is {2}'.format(die, total, int(ans[0])))

Number of ways 6 die can be thrown to sum 8 is 21


## Summary

Problem statement:
    
+ There are n identical dices. Each dice has given number of faces. In how many ways, you can get the given sum.

In this lab we look at a programming technique called dynamic programming to solve a combinatorics problem involving the sum of rolling _n_ number of die. We generate a j x k matrix to store our solutions, and using recursive relation fill in the number of dice where each face can be added together to a specified sum. 

__Algorithmic complexity__:  O(faces * die * total)